srt/urls.py
from django.urls import path

# from . import views # views 디렉터리의 __init__.py 파일에서모든 뷰 파일의 함수를 import 했기 때문에 urls.py와 같은 다른 모듈에서 views 모듈의 함수를 사용하는 부분을 수정할 필요가 없다.
from . import views

# 네임스페이스
app_name = 'srt'

urlpatterns = [
    path('', views.index, name='index'),                             # 디폴트로 index에 연결 (www.host/srt 일 때)
    path('beforemecro', views.beforemecro, name='beforemecro'),      
    path('mypage', views.mypage, name='mypage'),                     
    path('domecro', views.do_mecro, name='domecro'),                 
    path('celerytest', views.celerytest, name='celerytest'),         
    path('celeryresult/<str:task_id>/', views.check_task_result, name='check_task_result'),



]

srtproject/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import base_views
from srt import views


urlpatterns = [
    path('', views.index, name = 'index'),

    path('admin/', admin.site.urls),
    path('api/', include('main.urls')), # url main이 붙으면 main app에서 정리한 urls를 활용
    path('common/', include('common.urls')),  # url common이 붙으면 common app에서 정리한 urls를 활용
    path('srt/', include('srt.urls')),
]

handler404 = 'common.views.page_not_found'

srt/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

from django.conf import settings
# Create your models here.


#  매크로 신청 정보 MASTER: mecro_case
class MecroMaster(models.Model):

    client = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='mecro_case')  # User.mecro_case.all() -> 해당 유저가 신청한 매크로 건들
    mecro_id = models.CharField(max_length=200) # 매크로 신청 건 고유 번호
    korailID = models.CharField(max_length=50)  # 코레일 계정 id
    time_in = models.DateTimeField(null=True)   # 신청 시간 
    time_out = models.DateTimeField(null=True)  # 완료 시간
    dep  = models.CharField(max_length=200)
    arr = models.CharField(max_length=200)
    date  = models.CharField(max_length=200)
    dep_time_from = models.CharField(max_length=200)
    dep_time_to	 = models.CharField(max_length=200)
    first_seat_YN = models.CharField(max_length=10)
    
    task_ID = models.CharField(max_length=200, default='0000000') # celery 작업 id
    status = models.CharField(max_length=10)  # 진행 상태
    train_no = models.CharField(max_length=50, null=True)  # (예약 완료시) 열차번호

    def __str__(self):
        return self.mecro_id

srt/forms.py
from django import forms
from .station_info import STATION_LIST

choices = [(k,k) for k in STATION_LIST]

class TrainSearchForm(forms.Form):
    departure_station = forms.ChoiceField(choices=choices, label='출발 역')
    arrival_station = forms.ChoiceField(choices=choices, label='도착 역')
    departure_time_from = forms.TimeField(label='출발 시간(시작)')
    departure_time_to = forms.TimeField(label='출발 시간(종료)')
    departure_date = forms.DateField(label='출발 일자')

class SrtAccountForm(forms.Form):
    srt_id = forms.CharField()
    srt_pw = forms.CharField()

srt/views.py
from django.shortcuts import render, redirect
import json
from SRT import SRT
from SRT import SeatType
from .forms import TrainSearchForm, SrtAccountForm
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
import time
from .station_info import STATION_LIST
import requests
# Create your views here.
from celery.result import AsyncResult
from srt.tasks import add, excute_mecro
from .models import MecroMaster
from django.utils import timezone


def index(request):

    now = datetime.now()
    now_af_1hour = now + timedelta(hours=1)  # 현재 시간에 1시간을 추가한 값
    if request.method == 'POST':
        form = TrainSearchForm(request.POST)
        print(form.is_valid())

        if form.is_valid():
            request.session['departure_station'] = request.POST['departure_station']
            request.session['arrival_station'] = request.POST['arrival_station']
            request.session['departure_time_to'] = request.POST['departure_time_to']
            request.session['departure_time_from'] = request.POST['departure_time_from']
            request.session['departure_date'] = request.POST['departure_date']

            departure_station = form.cleaned_data['departure_station']
            arrival_station = form.cleaned_data['arrival_station']
            departure_time_to = form.cleaned_data['departure_time_to'].strftime("%H%M%S")
            departure_time_from = form.cleaned_data['departure_time_from'].strftime("%H%M%S")
            departure_date = form.cleaned_data['departure_date'].strftime("%Y%m%d")
            srt = SRT("2392619471", "Han0128!!") # SRT('id','pw')
            trains = srt.search_train(departure_station, arrival_station, departure_date, departure_time_from, departure_time_to, available_only=False) 
            
            context = {'departure_station': departure_station, 'arrival_station': arrival_station, 'departure_time_from': departure_time_from,  'departure_time_to': departure_time_to, 'departure_date' : departure_date, "trains" : trains}
            print(context)

            return render(request, 'srt/srt_train_list.html', context)

    else:
        form = TrainSearchForm()

    return render(request, 'srt/index.html', {'form': form, 'now': now, 'now_af_1hour': now_af_1hour, "station_list": STATION_LIST})



def beforemecro(request):
    return render(request, 'srt/srt_train_before_mecro.html')


@login_required(login_url='common:login')  # 로그인 안한사람은 함수가 실행되지 않고 login url 타도록.
def mypage(request):
    context = {
        'mecro_cases': MecroMaster.objects.filter(client=request.user)
    }
    return render(request, 'srt/srt_mypage.html', context)





def celerytest(request):
    # 작업 시작 및 작업 ID 저장
    result = add.delay(4, 3)
    task_id = result.id
    
    # 작업의 결과를 즉시 확인하려면(블로킹 방식)
    # result = result.get(timeout=10)  # 10초 안에 작업이 완료되지 않으면 예외 발생
    
    # introduce_data 사전에 작업 ID를 저장
    introduce_data = {'task_id': task_id}
    return render(request, 'srt/celerytest.html', introduce_data)


# task_id만 있으면 확인 가능 [공통]
def check_task_result(request, task_id):
    # 작업 결과 조회
    result = AsyncResult(task_id)
    if result.state == 'SUCCESS':
        introduce_data = {'result': result.result}
    else:
        introduce_data = {'result': '작업이 아직 완료되지 않았습니다.'}
    return render(request, 'srt/celerytest.html', introduce_data)



def do_mecro(request):
    if request.method == 'POST':
        form = SrtAccountForm(request.POST)

        if form.is_valid():
            # DB에 1 건 추가
            Mecro_id = str(request.user) + '_' + str(MecroMaster.objects.filter(client = request.user).count() + 1 ).zfill(6)
            
            reservation_info = {
                'mecro_id': Mecro_id,
                'srt_id' : form.cleaned_data['srt_id'],
                'srt_pw' : form.cleaned_data['srt_pw'],
                'dep'  : request.session.get('departure_station'),
                'arr'  : request.session.get('arrival_station'),
                'dep_time_from'  : request.session.get('departure_time_from').replace(':','') + '00',
                'dep_time_to'  : request.session.get('departure_time_to').replace(':','') + '00',
                'date'  : request.session.get('departure_date').replace('-',''),
                'receiveNos' : '01029361595',
                }

            # DB에 1 건 추가
            MecroMaster.objects.create(
                mecro_id = Mecro_id,
                # train_no = '',
                dep= reservation_info['dep'],
                arr = reservation_info['arr'],
                date = reservation_info['date'],
                dep_time_from = reservation_info['dep_time_from'],
                dep_time_to = reservation_info['dep_time_to'],
                # task_ID = task_id,
                first_seat_YN = 'N',
                client = request.user,   # id 로 저장됨 
                status= '1' ,
                )

            # 비동기 처리 시작
            excute_mecro.delay(reservation_info)

            # # MecroMaster DB에 task_id 저장해야 함
            # task_id = TASK.id
            # MecroMaster.objects.filter(mecro_id = Mecro_id).update(task_ID=task_id)


            # introduce_data = {'task_id': task_id}

        return redirect('srt:mypage')




def sendMSG(text, receiveNos):

    url = 'https://api.sendm.co.kr/v1/sms/send'

    headers={
        # (http://13.209.12.46/)서버용 api-key: db92eeab6b79469b8cd280b6bb757cd9 -> 배포 올릴때 꼭 이 키를 사용
        "user-id" : "NA_20240415173755",
        "api-key" : "db92eeab6b79469b8cd280b6bb757cd9"
    }

    
    request_data = {
        "callerNo": "01029361595", # 발신자는 고정
        "message": text,
        "receiveNos": receiveNos
    }

    try:
        response = requests.post(url, headers= headers,  json=request_data)
        res_obj = json.loads(response.text)
        if res_obj['code'] == '200':
            print(f'문자전송 성공: {text}')
        else: 
            print(f'문자전송 실패: {res_obj}')
    except:
        print('문자전송 실패: 네트워크 오류')

templates/srt/celerytest.html
<!DOCTYPE html>
<html>
<head>
    <title>Introduce</title>
</head>
<body>
    {% if result %}
        <p>결과: {{ result }}</p>
    {% else %}
        <p>작업이 처리 중입니다. 결과를 확인하려면 <a href="{% url 'srt:check_task_result' task_id %}">여기</a>를 클릭하세요.</p>
    {% endif %}
</body>
</html>

templates/srt/index.html
{% extends 'base_SRT.html' %}
{% load static %}
{% block content %}

<!-- 출처 : https://bootstrapmade.com/bikin-free-simple-landing-page-template/ -->


<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center" style="margin-top: 120px;">
    <div class="container d-flex flex-column align-items-center justify-content-center" data-aos="fade-up">
        <h1> 기차를 놓쳤다면? </h1>
        <h2> SRT 자동 매크로 & 문자 알람 시스템</h2>
        <a href="#about" class="btn-get-started scrollto"> 매크로 시작</a>
        <img src= "{% static 'assets/img/hero-img.png' %}" class="img-fluid hero-img" alt="" data-aos="zoom-in" data-aos-delay="150">
        
    </div>
</section><!-- End Hero -->


<main id="main">
<!-- ======= Reservation Section ======= -->
<section id="about" class="about">
    <div class="container">

    <div class="row no-gutters">
        <div class="content col-xl-12 " data-aos="fade-right">
            <div class="content">
                <h3>SRT 자동 매크로 <br> & 문자 알람 시스템</h3>
                <div class="col-lg-6 mt-4 mt-md-0">
                    <form 
                    method="post"
                    style="
                    margin-top: 10px;
                    margin-right: 10px;
                    margin-left: 10px;"
                    > 
                    {% csrf_token %}

                    <label for="departure_date" class="form-label col-md-3 col-12">출발 희망일</label>
                    <div class="mb-3">
                            <input type="date" class="form-control" id="departure_date" name="departure_date" value="{{now|date:'Y-m-d' }}">
                    </div>

                    <label for="departure_time_from" class="form-label col-md-3 col-4">출발 희망시간</label>
                    <div class="mb-3 row">
                        <div class="col-md-4 col-5">
                            <input type="time" class="form-control" id="departure_time_from" name="departure_time_from" value="{{ now|date:'H:i' }}">
                        </div>
                        <div class="col-md-1 col-2 text-center"> ~ </div>
                        <div class="col-md-4 col-5">
                            <input type="time" class="form-control" id="departure_time_to" name="departure_time_to" value="{{ now_af_1hour|date:'H:i' }}"> 
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="departure_station" class="form-label">출발 역</label>
                        <select class="form-select" id="departure_station" name="departure_station">
                            {% for station in station_list %}
                                {% if station == "수서" %}
                                    <option selected value={{ station }}> {{ station }}</option>
                                {% else %}
                                    <option value={{ station }}> {{ station }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="arrival_station" class="form-label">도착 역</label>
                        <select class="form-select" id="arrival_station" name="arrival_station">
                            {% for station in station_list %}
                                {% if station == "울산(통도사)" %}
                                    <option selected value={{ station }}> {{ station }}</option>
                                {% else %}
                                    <option value={{ station }}> {{ station }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <!-- <div class="mb-3">
                        <label for="phone-number" class="form-label col-md-3 col-8">휴대폰 번호 (하이픈 - 제외) </label>
                        <input type="tel" class="form-control" id="phone-number" name="phone-number" placeholder="휴대폰 번호를 입력하세요">
                    </div> -->


                    <button type="submit" class="btn btn-primary"> 검색 </button>
                </form>
                
                
                </div>
            </div>
        </div>

    </div>

    </div>
</section><!-- End Reservation Section -->

</main><!-- End #main -->


{% endblock %}

templates/srt/srt_mypage.html
{% extends 'base_SRT.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">

<div style="padding-bottom: 40px; "></div>
<h1 class="text-center" style="margin-bottom: 40px; color: #3b41f8e2; font-size: xx-large;"><strong> My page </strong></h1>

<h3><strong>내 정보</strong></h3>
<hr>
<div class="row">
    <div class="col-md-6">
        
    <p>ID: {{ user.username }} </p>
    <p>이메일: {{ user.email }} </p>
    <p>korailID: {{ user.korailID }} </p>
    </div>
    <div class="col-md-6">
    </div>
</div>
</div>

<div class="container mt-5">
<h3><strong>신청 내역</strong></h3>
<hr>
<table class="table table-striped">
    <thead>
    <tr>
        <th>열차번호</th>
        <th>출발 날짜</th>
        <th>출발 시간</th>
        <th>진행 상황</th>
        <!-- <th class="text-center">알람 서비스</th> -->
    </tr>
    </thead>

    <tbody>


        {% for case in mecro_cases %}
        <tr>
            <td> tmp </td>
            <td>{{ case.date }}</td>
            <td class="time">{{ case.dep_time_from }} ~ {{ case.dep_time_to }}</td>


            {% if case.status == "2" %}
            <td > <a href = "#" class="status">{{ case.status }}</a></td>
            {% else %}
            <td > <a href = "{% url 'srt:check_task_result' case.task_ID %}" class="status">{{ case.status }}</a></td>
            {% endif %}

        </tr>
        {% endfor %}


<!-- 
    <tr>
        <td>매크로 자동화 워크플로우</td>
        <td>2024-05-10</td>
        <td><i class="fas fa-circle-notch fa-spin"></i> 진행 중</td>
        <td class="text-center"> 
            <form action="{% url 'srt:domecro' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-sm btn-secondary" style="width: 60px;">시작</button>
            </form>
        </td>
    </tr>
-->
    </tbody>
</table>
</div>


{% endblock %}


{% block script %}
<script type='text/javascript'>


    document.addEventListener('DOMContentLoaded', function () {


        // 1.  시간 포맷 변경
        const timeElements = document.querySelectorAll('.time');

        function formatTime(timeStr) {
            if (timeStr.length === 6) {
                return timeStr.slice(0, 2) + ':' + timeStr.slice(2, 4);
            }
            return timeStr;
        }

        timeElements.forEach(function (element) {
            let times = element.textContent.split(' ~ ');
            let formattedTimes = times.map(formatTime);
            element.textContent = formattedTimes.join(' ~ ');
        });


        // 2.  진행 상황 lookup 
        const statusElements = document.querySelectorAll('.status');

        function formatStatus(statusstr) {
            if (statusstr == '0') {
                return '오류';
            }
            else if (statusstr == '1') {
                return '진행중';
            }
            else if (statusstr == '2') {
                return '완료';
            }
            return statusstr;
        }

        statusElements.forEach(function (element) {
            let status_text = formatStatus(element.textContent)
            element.textContent = status_text;
        });
    });












</script>
{% endblock %}

templates/srt/srt_train_before_mecro.html
{% extends 'base_SRT.html' %}
{% load static %}
{% block content %}

<section id="hero" class="d-flex align-items-start flex-column justify-content-center" style=" padding: 10px; margin-top: 120px;">

    <div class="w-100" style="margin-bottom: 15px;"> <strong>예약할 SRT 계정 정보를 입력하세요.</strong>   </div>

    <form 
    class = "w-100"
    method="post"
    action="{% url 'srt:domecro' %}" 
    style="
    margin-top: 10px;
    margin-right: 10px;"
    > 
    {% csrf_token %}
    <div class="row justify-content-center">
        <label for="departure_time_from" class="form-label col-md-12 col-12">SRT ID <br> (멤버십 번호 / 이메일 / 전화번호)</label>
        <div class="mb-3 w-25 border border-primary">
            <input type="text" class="form-control" id="srt_id" name="srt_id" value= {{ user.korailID }} >
        </div>
    </div>
    <div class="row justify-content-center">
        <label for="departure_time_from" class="form-label col-md-12 col-12">SRT 비밀번호</label>
        <div class="mb-3 w-25 border border-primary">
            <input type="password" class="form-control" id="srt_pw" name="srt_pw">
        </div>
    </div>
    <div>
        <input type="submit" value="매크로 시작" class="btn btn-primary" id="mecroButton">
    </div>
    
</form>





</section><!-- End Hero -->










{% endblock %}


{% block script %}
<script type='text/javascript'>
    const myButton = document.getElementById('mecroButton');

    // myButton.addEventListener('click', function() {
    // alert('개발중입니다!');
    // });
</script>
{% endblock %}

templates/srt/srt_train_list.html
{% extends 'base_SRT.html' %}
{% load static %}
{% block content %}

<section id="hero" class="d-flex align-items-start flex-column justify-content-center" style=" padding: 10px; margin-top: 120px; padding: 5dvh">
    {% if trains %}
    <div class="w-100" style="margin-bottom: 10px;"> 아래 열차 중에 예매됩니다. </div>

    <div class="list-group w-100" style="max-height: 400px; overflow-y: auto; margin-right: 20px; border: 2px solid #6c757d; border-radius: 0.25rem;">
        {% for train in trains %}
            <button type="button" class="list-group-item list-group-item-action " onclick="handleButtonClick(this)"> {{ train }}</button>
        {% endfor %}

    </div>



    <form action="{% url 'srt:beforemecro' %}" class="w-100 mb-3" style="margin-top: 20px;" method="post"  >
        {% csrf_token %}
    
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->


<!-- 
        <div class="mb-3">
            <input type="text" class="form-control" id="" name="">
        </div>
-->

        <div>
            <textarea type="hidden" name="content" id="selectedtrain" class="form-control mb-3" rows="1" style="display: none;"></textarea>        
            <input type="submit" value="다음" class="btn btn-primary">
        </div>
        
    </form>


    {% else %}
    <div class="w-100" style="margin-bottom: 10px;"> 예약 가능한 열차가 없습니다. </div>
    {% endif %}
</section><!-- End Hero -->





{% endblock %}


{% block script %}
<script type='text/javascript'>
    function handleButtonClick(button) {
        // 클릭한 버튼의 텍스트 가져오기
        var buttonText = button.textContent.trim();

        // form 요소에 버튼 텍스트 삽입
        document.getElementById("selectedtrain").value = buttonText;
        console.log("selectedtrain: " , document.getElementById("selectedtrain").value)

        // 모든 버튼의 클래스를 제거하여 선택된 버튼만 활성화 스타일을 적용
        var buttons = document.querySelectorAll('.list-group-item');
        buttons.forEach(function(btn) {
            btn.classList.remove('active');
        });
        button.classList.add('active');

    }
</script>
{% endblock %}

<style>
.list-group-item.active {
        background-color: #007bff;
        color: #fff;
    }
</style>