common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # 기본적으로 LoginView는 registration이라는 템플릿 디렉터리에서 login.html 파일을 찾는다.
    # 하지만 common 디렉터리에서 템플릿을 관리하고 싶기 때문에 template_name을 따로 지정한다.
    # 함수에서 템플릿에 User 객체를 전달하지 않더라도 템플릿에서는 django.contrib.auth 기능으로 인해 User 객체를 사용할 수 있다. 대표적으로 다음과 같은 것들이 있다. : user.is_authenticated / user.is_anonymous / user.username / user.is_superuser   
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),

]

main/urls.py
from django.urls import path

# from . import views # views 디렉터리의 __init__.py 파일에서모든 뷰 파일의 함수를 import 했기 때문에 urls.py와 같은 다른 모듈에서 views 모듈의 함수를 사용하는 부분을 수정할 필요가 없다.
from .views import base_views, question_views, answer_views



# 네임스페이스
app_name = 'main'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),                                                      # 디폴트로 index에 연결 (www.host/main 일 때)
    path('<int:question_id>/', base_views.detail, name='detail'),                                  # 뒤에 숫자가 붙었을 때 (www.host/main/{n} 일 때)

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),      # www.host/main/answer/create/{n}일 때
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),        # www.host/main/login 일 때


]

srt/urls.py
from django.urls import path

# from . import views # views 디렉터리의 __init__.py 파일에서모든 뷰 파일의 함수를 import 했기 때문에 urls.py와 같은 다른 모듈에서 views 모듈의 함수를 사용하는 부분을 수정할 필요가 없다.
from . import views

# 네임스페이스
app_name = 'srt'

urlpatterns = [
    path('', views.index, name='index'),                             # 디폴트로 index에 연결 (www.host/srt 일 때)
    path('beforemecro', views.beforemecro, name='beforemecro'),      
    path('mypage', views.mypage, name='mypage'),                     
    path('domecro', views.do_mecro, name='domecro'),                 
    path('celerytest', views.celerytest, name='celerytest'),         
    path('celeryresult/<str:task_id>/', views.check_task_result, name='check_task_result'),



]

srtproject/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import base_views
from srt import views


urlpatterns = [
    path('', views.index, name = 'index'),

    path('admin/', admin.site.urls),
    path('api/', include('main.urls')), # url main이 붙으면 main app에서 정리한 urls를 활용
    path('common/', include('common.urls')),  # url common이 붙으면 common app에서 정리한 urls를 활용
    path('srt/', include('srt.urls')),
]

handler404 = 'common.views.page_not_found'

main/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from ..models import Question


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색   icontains는 contains와 다르게 대소문자 구분을 안하고 찾는다.
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()


    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}


    return render(request, 'main/question_list.html', context)


# [./urls.py] path('<int:question_id>/', views.detail) → <int:question_id>가 자동으로 question_id에 들어간다.
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)              # 쿼리 결과가 없을 경우 404에러페이지로 이쁘게 렌더링하기 + pk는 primary key를 의미함.
    context = {'question': question}
    return render(request, 'main/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, Main API!</title>
</head>
<body>

    <!-- 네비게이션바: include로 가져올 수 있다. -->
    {% include "navbar.html" %}


    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->


    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->


    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/base_SRT.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title> SRT 매크로 알람 서비스 </title>
        <meta content="" name="description" />
        <meta content="" name="keywords" />

        <!-- Favicons -->
        <link href="{% static 'assets/img/favicon.png' %}" rel="icon" />
        <link href="{% static 'assets/img/apple-touch-icon.png' %} " rel="apple-touch-icon" />

        <!-- Google Fonts -->
        <link
            href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Krub:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
            rel="stylesheet"
        />

        <!-- Vendor CSS Files -->
        <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

        <!-- Template Main CSS File -->
        <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    </head>

    <body>


        {% include "srt_navbar.html" %}


        <!-- 기본 템플릿 안에 삽입될 내용 Start -->
        {% block content %} 
        {% endblock %}
        <!-- 기본 템플릿 안에 삽입될 내용 End -->



        {% include "srt_footer.html" %}


        <!-- 자바스크립트 Start -->
        {% block script %} {% endblock %}
        <!-- 자바스크립트 End -->






        <!-- Bootstrap JS -->
        <!-- <script src="{% static 'bootstrap.min.js' %}"></script> -->

        <!-- Vendor JS Files -->
        <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

        <!-- Template Main JS File -->
        <script src="{% static 'assets/js/main.js' %}"></script>



        
    </body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">Main API</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/srt_footer.html
<!-- ======= Footer ======= -->
<footer id="footer">

<div class="footer-top">
    <div class="container">
    <div class="row">

        <div class="col-lg-3 col-md-6 footer-contact">
        <h3>hminq</h3>
        <p>
            Ulsan <br>
            South Korea <br><br>
            <strong>Email:</strong> minku0128@naver.com<br>
        </p>
        </div>


    </div>
    </div>
</div>

<div class="container d-md-flex py-4">

    <div class="me-md-auto text-center text-md-start">
    <div class="copyright">
        &copy; Copyright <strong><span>Bikin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bikin-free-simple-landing-page-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
    </div>
    <div class="social-links text-center text-md-right pt-3 pt-md-0">
    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    </div>
</div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

templates/srt_navbar.html
<!-- ======= Header ======= -->
<header id="header" class="fixed-top" style="height: 68px;">
    <div class="container d-flex align-items-center justify-content-between">
    
        <h1 class="logo"><a href="{% url 'srt:index' %}"> Mincro </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        
        <!-- <a class="d-flex flex-row nav-link scrollto active" href="{% url 'common:login' %}" style="font-size: 18px;">
            <i class="bi bi-box-arrow-in-right" style="font-size: 30px; margin-right: 8px;"></i>
            <div class="hide-on-mobile" style="margin-top: 10px;">로그인</div>
        </a> -->
        <nav id="navbar" class="navbar">

        
        {% if user.is_authenticated %}
        <a style="color: #3b4ef8ee;" href="{% url 'srt:mypage' %}">
            <i class="bi bi-person" style="font-size: 27px;"></i>
        </a>
        <a class="d-flex flex-row nav-link scrollto active" href="{% url 'common:logout' %}" style="font-size: 20px; padding-left: 11px;">
            {{ user.username }} 
            <div class="hide-on-mobile" style="margin-top: 2px; font-size: 13px; color: #3b4ef8ee;"> &nbsp; (로그아웃)</div>
        </a>

        {% else %}
        <a style="color: #3b4ef8ee;" href="{% url 'srt:mypage' %}">
            <i class="bi bi-person" style="font-size: 27px;"></i>
        </a>
        <a class="d-flex flex-row nav-link scrollto active" href="{% url 'common:login' %}" style="font-size: 18px; padding-left: 11px; ">
            <i class="bi bi-box-arrow-in-right" style="font-size: 30px; margin-right: 8px;"></i>
            <div class="hide-on-mobile" style="margin-top: 2px;"></div>
        </a>
        </nav><!-- .navbar -->

        {% endif %}
    </div>
</header><!-- End Header -->

<style>
    /* 300px 이하에서만 작동 */
    @media (max-width: 300px) {
    .hide-on-mobile {
        display: none;
    }
    }

</style>